export enum ProgrammingSkill {
  HTML = "HTML",
  CSS = "CSS",
  JAVA_SCRIPT = "Javascript",
  TYPE_SCRIPT = "TypeScript",
  REACT_JS = "React.js",
  NEXT_JS = "Next.js",
  VUE_JS = "Vue.js",
  NUXT_JS = "Nuxt.js",
  ANGULAR_JS = "Angular.js",
  PYTHON = "Python",
  // C = "C",
  C_SHARP = "C#",
  C_PLUSPLUS = "C++",
  // OBJECTIVE_C = "Object-C",
  JAVA = "Java",
  // VB_SCRIPT = "VBScript",
  // COBOL = "COBOL",
  PERL = "Perl",
  PHP = "PHP",
  RUBY = "RUBY",
  GO = "Go",
  RUST = "Rust",
  // R = "R",
  SWIFT = "Swift",
  DART = "Dart",
  SQL = "SQL",
  // NO_SQL = "NoSQL",
  // DOCKER = "Docker",
  // KUBERNETES = "Kubernetes",
  // GCP = "GCP",
  // AWS = "AWS",
  // GIT = "Git",
}

export const ProgrammingSkillIcons = {
  [ProgrammingSkill.HTML]: "/html-5.svg",
  [ProgrammingSkill.CSS]: "/css-3.svg",
  [ProgrammingSkill.JAVA_SCRIPT]: "/javascript.svg",
  [ProgrammingSkill.TYPE_SCRIPT]: "/typescript-icon.svg",
  [ProgrammingSkill.REACT_JS]: "/react.svg",
  [ProgrammingSkill.NEXT_JS]: "/nextjs-icon.svg",
  [ProgrammingSkill.VUE_JS]: "/vue.svg",
  [ProgrammingSkill.NUXT_JS]: "/nuxt-icon.svg",
  [ProgrammingSkill.ANGULAR_JS]: "/angular-icon.svg",
  [ProgrammingSkill.JAVA]: "/java.svg",
  [ProgrammingSkill.PYTHON]: "/python.svg",
  [ProgrammingSkill.PHP]: "/php.svg",
  [ProgrammingSkill.RUBY]: "/ruby.svg",
  [ProgrammingSkill.GO]: "/go.svg",
  [ProgrammingSkill.C_SHARP]: "/c-sharp.svg",
  [ProgrammingSkill.C_PLUSPLUS]: "/c-plusplus.svg",
  [ProgrammingSkill.PERL]: "/perl.svg",
  [ProgrammingSkill.RUST]: "/rust.svg",
  [ProgrammingSkill.SWIFT]: "/swift.svg",
  [ProgrammingSkill.DART]: "/dart.svg",
  [ProgrammingSkill.SQL]: "/mysql.svg",
};
